### PR TITLE
Fix PgPool Deprecation Issue

### LINKED ISSUE #41: FIx the PgPool Deprecation issue

### PR DESCRIPTION
**Pull request by ShivamNagpal**
closes #41 #42

### CODE REVIEW

File: src/main/java/dev/shivamnagpal/users/dtos/internal/SessionPayload.java [hunk 1]
```diff
@@ -5,17 +5,10 @@
 import dev.shivamnagpal.users.utils.MessageConstants;
 import io.netty.handler.codec.http.HttpResponseStatus;
 import io.vertx.core.Future;
-import lombok.Getter;
-import lombok.NoArgsConstructor;
-import lombok.Setter;
+import lombok.*;
```
Comment (astha-singh-dev) [inline src/main/java/dev/shivamnagpal/users/dtos/internal/SessionPayload.java:8]: nit: Replace Wild Card Imports with Specific Import

**Review by astha-singh-dev — APPROVED** [review]

**Review by astha-singh-dev — APPROVED** [review]
