### PR TITLE
fix: #45 | Fix the ResponseWrapper.failure() overload deprecation

### LINKED ISSUE #45: Fix the Deprecated ResponseWrapper failure method

### PR DESCRIPTION
**Pull request by ShivamNagpal**
closes #45

### CODE REVIEW

File: src/main/java/dev/shivamnagpal/users/dtos/response/ResponseWrapper.java [hunk 1]
```diff
@@ -30,13 +30,12 @@ public static <T> ResponseWrapper<T> success(T payload) {
...
-    public static <T> ResponseWrapper<T> failure(T payload, String message) {
-        return new ResponseWrapper<>(null, false, payload, message);
+    public static <T> ResponseWrapper<T> failure(List<ErrorResponse> errors) {
+        return failure(errors, null);
     }
 
-    public static <T> ResponseWrapper<T> failure(List<ErrorResponse> errors) {
-        return new ResponseWrapper<>(errors, false, null, null);
+    public static <T> ResponseWrapper<T> failure(List<ErrorResponse> errors, T payload) {
+        return new ResponseWrapper<>(errors, false, payload, null);
```
Comment (ShivamNagpal) [inline src/main/java/dev/shivamnagpal/users/dtos/response/ResponseWrapper.java:38]: So for failure(), errors have to be there and payload is optional now.

We cannot go about not having payload because of one specific use case. If we change the user interaction flow, then there is a way to get rid of this method altogether.

**Review by astha-singh-dev — APPROVED** [review]
